version: '3'
services:
  web:
    image: jslee4577/fitple-project:latest
    container_name: web-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitple_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ENV_VAR: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: db-container
    environment:
      MYSQL_DATABASE: fitple_project
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p12345678"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

networks:
  my_network: