### 유저 회원가입
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "userName": "세로토닌",
  "balance": 19384,
  "accountId": "tryptophan204",
  "password": "vitaminB6",
  "confirmPassword": "vitaminB6",
  "email": "5HTP@naver.com",
  "phoneNumber": "01011117678",
  "residentRegistrationNumber": "123451189123",
  "foreignerRegistrationNumber": ""
}

### 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "tryptophan204",
  "password": "vitaminB6"
}

> {%
  client.test("로그인 성공", function() {
    var response = client.global.response;
    var jsonResponse = JSON.parse(response.body);
    var accessToken = response.headers["authorization"].substring(7);
    client.global.set("accessToken", accessToken);
  });
%}

### 응답에서 access_token을 추출하여 변수에 저장
@access_token = your_access_token_here

### 결제 요청 정보 임시 저장
POST http://localhost:8080/api/pt-payments/test/payment-information
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ3Njc5LCJleHAiOjE3MjI0NDk0Nzl9.y-Dm7iTYKFwAex1Lo7vSv-eHCq280F80bs5h_8xg5_8

{
  "trainerId": 2,
  "userId": 5,
  "ptTimes": "TWENTY_TIMES"
}

### 트레이너와 유저 검증
GET http://localhost:8080/api/pt-payments/test/validate/3/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ3Njc5LCJleHAiOjE3MjI0NDk0Nzl9.y-Dm7iTYKFwAex1Lo7vSv-eHCq280F80bs5h_8xg5_8

### 중복 PT 예약 체크
GET http://localhost:8080/api/pt-payments/test/check-duplicate/2/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ1NzA3LCJleHAiOjE3MjI0NDc1MDd9.SzDD7NGbXu_c0Qem7frU4m1FZc1UFSb8gfkj3dvRoJo

### 결제 페이지 조회
GET http://localhost:8080/api/pt-payments/test/paymentpage/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ1NzA3LCJleHAiOjE3MjI0NDc1MDd9.SzDD7NGbXu_c0Qem7frU4m1FZc1UFSb8gfkj3dvRoJo

### pt 횟수 선택 총액
POST http://localhost:8080/api/pt-payments/test/select-PtTimes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ3Njc5LCJleHAiOjE3MjI0NDk0Nzl9.y-Dm7iTYKFwAex1Lo7vSv-eHCq280F80bs5h_8xg5_8

{
    "selectedTimes": "TEN_TIMES",
    "trainerPrice": 100.0
}

### api요청 전 결제 정보 저장
POST http://localhost:8080/api/pt-payments/test/save-payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cnlwdG9waGFuMjA0IiwiaWF0IjoxNzIyNDQ5NTQ0LCJleHAiOjE3MjI0NTEzNDR9.YaknYAKSwEX-cUJJm4tjozt3Txv9qC_BWwEK_tgHjKQ

{
  "trainerId": 2,
  "userId": 5,
  "ptTimes": "SIXTY_TIMES",
  "paymentType": "UNDEFINED",
  "amount": 100.0
}