### 점주 프로필 조회
GET http://localhost:8080/api/profile/owner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZWwxMjExMSIsImlhdCI6MTcyMTk4ODg3MCwiZXhwIjoxNzIxOTkwNjcwfQ.C36lwh8UUAc_Wkbuex6-ipECXrrX0PkYZtyL1VP86Xo

### 점주 회원가입
POST http://localhost:8080/api/owners/signup
Content-Type: application/json

{
  "ownerName": "손아엘점주",
  "accountId": "ael12111",
  "password": "ael121667",
  "confirmPassword": "ael121667",
  "email": "ael121wjawn@naver.com",
  "phoneNumber": "01012345678",
  "residentRegistrationNumber": "123456789123",
  "foreignerRegistrationNumber": "123456789123",
  "businessName": "100003333"
}

### 점주 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "ael12111",
  "password": "ael121667"
}

### 점주 프로필 변경
PUT http://localhost:8080/api/profile/owner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZWwxMjExMSIsImlhdCI6MTcyMjI4MjQ4OSwiZXhwIjoxNzIyMjg0Mjg5fQ.End-uDnwNBRDTnG0QB5wDtZ1A12RZPHew24Cs_QxNf4

{
  "nickname": "점아에링링",
  "email":"sss@naver.com",
  "ownerPicture": "점사진인데임",
  "zipcode": "점우편번호임",
  "mainAddress": "점메인주소임",
  "detailedAddress": "점디테일주소임",
  "ownerPhoneNumber": "01099998888",
  "password": "ael121667"
}

### 점주 비번 변경
PUT http://localhost:8080/api/profile/owner/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZWwxMjExMSIsImlhdCI6MTcyMTk5MDcyOCwiZXhwIjoxNzIxOTkyNTI4fQ.345K5UslnBgyBOhMqJD7z6pVpBgK3x7wStCcxvn3t04

{
  "oldPassword": "ael121667",
  "newPassword": "심재훈"
}