### 유저 회원가입
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "userName": "손아엘",
  "accountId": "ael121",
  "password": "ael121667",
  "confirmPassword": "ael121667",
  "email": "ael121@naver.com",
  "phoneNumber": "01012345678",
  "residentRegistrationNumber": "123456789123",
  "foreignerRegistrationNumber": "123456789123"
}

### 유저 회원가입
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "userName": "세로토닌",
  "balance": 19384,
  "accountId": "tryptophan204",
  "password": "vitaminB6",
  "confirmPassword": "vitaminB6",
  "email": "5HTP@naver.com",
  "phoneNumber": "01011117678",
  "residentRegistrationNumber": "123451189123",
  "foreignerRegistrationNumber": ""
}


### 유저 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "ael121",
  "password": "ael121667"
}

### 유저 프로필 변경
PUT http://localhost:8080/api/profile/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZWwxMjEiLCJpYXQiOjE3MjE5MzE2NzksImV4cCI6MTcyMTkzMzQ3OX0.bz2-E8Ncejw2Hmizs2E4ZC0X4vRSCpTLwdnFlzkE8qI

{
  "nickname": "아에링링",
  "zipcode": "우편번호임",
  "mainAddress": "메인주소임",
  "detailedAddress": "디테일주소임",
  "userPicture": "사진인데임",
  "password": "ael121667"
}

### 유저 비번 변경
PUT http://localhost:8080/api/profile/users/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLslYTsnbTrlJQiLCJpYXQiOjE3MjE4MzI2NjQsImV4cCI6MTcyMTgzNDQ2NH0.IdUkhoYwZgWzluz8a4AWkcGNsbmEpF0x4_nlBog4gck

{
  "oldPassword": "비밀번호바꿈",
  "newPassword": "심재훈"
}

### 유저 프로필 조회
GET http://localhost:8080/api/profile/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZWwxMjEiLCJpYXQiOjE3MjE5MzE2NzksImV4cCI6MTcyMTkzMzQ3OX0.bz2-E8Ncejw2Hmizs2E4ZC0X4vRSCpTLwdnFlzkE8qI

{

}