### 회원가입
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "userName": "testuser",
  "accountId": "testaccount",
  "password": "testpassword",
  "confirmPassword": "testpassword",
  "email": "testuser@example.com"
}


### 점주 회원가입
POST http://localhost:8080/api/owners/signup
Content-Type: application/json

{
"ownerName": "Test Owner",
"residentRegistrationNumber": "1234567890123",
"foreignerRegistrationNumber": "",
"isForeigner": false,
"accountId": "testowner",
"password": "password123",
"confirmPassword": "password123",
"nickname": "owner123",
"email": "testowner@example.com",
"businessRegistrationNumber": "1234567890",
"zipcode": "12345",
"mainAddress": "Main St 123",
"detailedAddress": "Apt 456",
"ownerPhoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "testaccount",
  "password": "testpassword"
}

> {%
  client.test("로그인 성공", function() {
    var response = client.response;
    var jsonResponse = JSON.parse(response.body);
    var accessToken = response.headers["Authorization"].substring(7);
    client.global.set("accessToken", accessToken);
  });
%}

### 점주 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "testowner",
  "password": "password123"
}

> {%
  client.test("로그인 성공", function() {
    var response = client.response;
    var jsonResponse = JSON.parse(response.body);
    var accessToken = response.headers["Authorization"].substring(7);
    var accessToken = response.headers["Authorization"].substring(7); // "Bearer " 제거
    client.global.set("accessToken", accessToken);
  });
%}

### 로그아웃
POST http://localhost:8080/api/logout


### 점주 로그아웃
POST http://localhost:8080/api/logout

### 점주 회원탈퇴
DELETE http://localhost:8080/api/profile/owners/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0YWNjb3VudCIsImlhdCI6MTcyMTgxNjgwMSwiZXhwIjoxNzIxODE4NjAxfQ.5f-ClM-xTVOvs--SumAsoap2nrUaAKXLDkWIs9h4w5M

### 회원탈퇴
DELETE http://localhost:8080/api/profile/users/signout

### 점주 회원탈퇴
DELETE http://localhost:8080/api/profile/owners/signout

### 회원탈퇴
DELETE http://localhost:8080/api/profile/users/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZjMzMTIxIiwiaWF0IjoxNzIyMzc1OTYzLCJleHAiOjE3MjIzNzc3NjN9.6eOnctw9-Ih1z55viHwevy5kShYYymzvSFfMzMEPQQk


### 회원탈퇴
DELETE http://localhost:8080/api/profile/users/signout